// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace fussballliga.Models
{
    public partial class Goal
    {
        [Key]
        public int Minute { get; set; }
        [Key]
        public int GameId { get; set; }
        public int? TeamPlayerId { get; set; }

        [ForeignKey("GameId")]
        [InverseProperty("Goals")]
        public virtual Game Game { get; set; }
        [ForeignKey("TeamPlayerId")]
        [InverseProperty("Goals")]
        public virtual TeamPlayer TeamPlayer { get; set; }
    }
}