// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace fussballliga.Models
{
    [Table("League")]
    public partial class League
    {
        public League()
        {
            Teams = new HashSet<Team>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column(TypeName = "date")]
        public DateTime CreatedOn { get; set; }

        [InverseProperty("League")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}