// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace fussballliga.Models
{
    [Table("TeamTrainer")]
    public partial class TeamTrainer
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime TrainerFrom { get; set; }
        [Column(TypeName = "date")]
        public DateTime? TrainerTo { get; set; }
        public int? TrainerId { get; set; }
        public int? TeamId { get; set; }

        [ForeignKey("TeamId")]
        [InverseProperty("TeamTrainers")]
        public virtual Team Team { get; set; }
        [ForeignKey("TrainerId")]
        [InverseProperty("TeamTrainers")]
        public virtual Trainer Trainer { get; set; }
    }
}