// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace fussballliga.Models
{
    [Table("Trainer")]
    public partial class Trainer
    {
        public Trainer()
        {
            TeamTrainers = new HashSet<TeamTrainer>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column(TypeName = "date")]
        public DateTime BirthDate { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Nation { get; set; }

        [InverseProperty("Trainer")]
        public virtual ICollection<TeamTrainer> TeamTrainers { get; set; }
    }
}