entity League{
    * Id <<PK>>
    --
    * name
    * createdOn
}

entity Team{
    * Id <<PK>>
    --
    * name
    league <<FK>>
}

entity Player{
    * Id <<PK>>
    --
    * name
    * birthdate
    nation
}

entity TeamTrainer{
    * Id <<generated>>
    ---
    * TrainerFrom
    TrainerTo
    TrainerId <<FK>>
    TeamId <<FK>>
    
}

entity Goals{
    * Minutue <<PK>>
    * GameId <<FK>>
    --
    * TeamPlayerId <<FK>>
}

entity TeamPlayer{
    * Id <<generated>>
    ---
    * PlayerFrom
    PlayerTo
    PlayerId <<FK>>
    TeamId <<FK>>
    
}

entity Trainer{
    * Id <<PK>> 
    --
    * name 
    * birthdate 
    nation
}

entity Game {
    * Id <<PK>> 
    --
    * gameDay
    * gameDate
    homeTeam <<FK>>
    awayTeam <<FK>>
    
}
League ||--o{ Team
Team ||--o{ TeamTrainer
Team ||--o{ TeamPlayer
Team ||--o{ Game
Team ||--o{ Game
Player ||--o{ TeamPlayer
Trainer ||--o{ TeamTrainer
Game ||--o{ Goals
TeamPlayer ||--o{ Goals
