// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NationsLeague.Models
{
    [Table("Trainer")]
    public partial class Trainer
    {
        public Trainer()
        {
            TeamTrainers = new HashSet<TeamTrainer>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Firstname { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Lastname { get; set; }
        [Column(TypeName = "date")]
        public DateTime BirthDate { get; set; }
        public int? NationalityId { get; set; }

        [ForeignKey("NationalityId")]
        [InverseProperty("Trainers")]
        public virtual Nationality Nationality { get; set; }
        [InverseProperty("Trainer")]
        public virtual ICollection<TeamTrainer> TeamTrainers { get; set; }
    }
}